vmbuilder kvm ubuntu \
        --dest=/mnt/storage/vm \
        --overwrite \
        --mem=1024 \
        --cpus=1 \
        --rootsize=7168 \
        --swapsize=1024 \
        --ip=192.168.1.201 \
        --mask=255.255.255.0 \
        --bcast=192.168.1.255 \
        --gw=192.168.1.1 \
        --addpkg=openssh-server \
        --addpkg=vim \
        --addpkg=cron \
        --addpkg=acpid \
        #--addpkg=linux-image-generic \ #you only need this if you encounter an error related to non-PAE cpus.
        --arch=amd64 \
        --suite=trusty \
        --flavour virtual \
        --components main,universe,restricted \
        --hostname HOSTNAME \
        --user USERNAME \ 
        --pass SECURE_PASSWORD \
        --libvirt qemu:///system \
        --bridge=br0 ;